### ISSUE TITLE
Provide image for v1.28.0 version

### ISSUE THREAD

**Issue by EBMBA** [clastix/kubectl#24]
Hi, 

Are you working on providing v1.28 kubectl image to resolve installation issues on the last version of Kubernetes please ? 

Failed to pull image "clastix/kubectl:v1.28": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/clastix/kubectl:v1.28": failed to resolve reference "docker.io/clastix/kubectl:v1.28": docker.io/clastix/kubectl:v1.28: not found

**Comment by prometherion** [comment]
Sorry for being late, and thanks for opening this issue.

I just triggered the request for building a v1.28 compatible `kubectl` image, once the [job](https://github.com/clastix/kubectl/actions/runs/6550379983/job/17789369631) is finished it should be available.

Feel free to close once ensured the artifact is there!

**Comment by EBMBA** [comment]
Thanks !
